//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class administrator_sr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal administrator_sr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("backend.Translations.administrator_sr", typeof(administrator_sr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string h1naslov {
            get {
                return ResourceManager.GetString("h1naslov", resourceCulture);
            }
        }
        
        internal static string lblsort {
            get {
                return ResourceManager.GetString("lblsort", resourceCulture);
            }
        }
        
        internal static string op1 {
            get {
                return ResourceManager.GetString("op1", resourceCulture);
            }
        }
        
        internal static string op2 {
            get {
                return ResourceManager.GetString("op2", resourceCulture);
            }
        }
        
        internal static string clanovi {
            get {
                return ResourceManager.GetString("clanovi", resourceCulture);
            }
        }
        
        internal static string treneri {
            get {
                return ResourceManager.GetString("treneri", resourceCulture);
            }
        }
        
        internal static string personalnitreneri {
            get {
                return ResourceManager.GetString("personalnitreneri", resourceCulture);
            }
        }
        
        internal static string prikazivise {
            get {
                return ResourceManager.GetString("prikazivise", resourceCulture);
            }
        }
        
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        internal static string primeni {
            get {
                return ResourceManager.GetString("primeni", resourceCulture);
            }
        }
        
        internal static string suredelete {
            get {
                return ResourceManager.GetString("suredelete", resourceCulture);
            }
        }
        
        internal static string conf {
            get {
                return ResourceManager.GetString("conf", resourceCulture);
            }
        }
        
        internal static string canc {
            get {
                return ResourceManager.GetString("canc", resourceCulture);
            }
        }
        
        internal static string sureUser {
            get {
                return ResourceManager.GetString("sureUser", resourceCulture);
            }
        }
        
        internal static string nam {
            get {
                return ResourceManager.GetString("nam", resourceCulture);
            }
        }
        
        internal static string prc {
            get {
                return ResourceManager.GetString("prc", resourceCulture);
            }
        }
        
        internal static string op {
            get {
                return ResourceManager.GetString("op", resourceCulture);
            }
        }
        
        internal static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        internal static string quan {
            get {
                return ResourceManager.GetString("quan", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string prod {
            get {
                return ResourceManager.GetString("prod", resourceCulture);
            }
        }
        
        internal static string adp {
            get {
                return ResourceManager.GetString("adp", resourceCulture);
            }
        }
        
        internal static string shwp {
            get {
                return ResourceManager.GetString("shwp", resourceCulture);
            }
        }
        
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        internal static string cls {
            get {
                return ResourceManager.GetString("cls", resourceCulture);
            }
        }
        
        internal static string trn {
            get {
                return ResourceManager.GetString("trn", resourceCulture);
            }
        }
    }
}
