//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class headerfooter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal headerfooter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("backend.Translations.headerfooter", typeof(headerfooter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string ful1p1 {
            get {
                return ResourceManager.GetString("ful1p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string ful1p2 {
            get {
                return ResourceManager.GetString("ful1p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ful1p3 {
            get {
                return ResourceManager.GetString("ful1p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string ful2p1 {
            get {
                return ResourceManager.GetString("ful2p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports gear.
        /// </summary>
        public static string ful2p2 {
            get {
                return ResourceManager.GetString("ful2p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes.
        /// </summary>
        public static string ful2p3 {
            get {
                return ResourceManager.GetString("ful2p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footwear.
        /// </summary>
        public static string ful2p4 {
            get {
                return ResourceManager.GetString("ful2p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplements.
        /// </summary>
        public static string ful2p5 {
            get {
                return ResourceManager.GetString("ful2p5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        public static string ful3p1 {
            get {
                return ResourceManager.GetString("ful3p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string hul1 {
            get {
                return ResourceManager.GetString("hul1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string hul10 {
            get {
                return ResourceManager.GetString("hul10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string hul2 {
            get {
                return ResourceManager.GetString("hul2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string hul3 {
            get {
                return ResourceManager.GetString("hul3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string hul4 {
            get {
                return ResourceManager.GetString("hul4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the change.
        /// </summary>
        public static string hul5 {
            get {
                return ResourceManager.GetString("hul5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string hul6 {
            get {
                return ResourceManager.GetString("hul6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        public static string hul7 {
            get {
                return ResourceManager.GetString("hul7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string hul8 {
            get {
                return ResourceManager.GetString("hul8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainers.
        /// </summary>
        public static string hul9 {
            get {
                return ResourceManager.GetString("hul9", resourceCulture);
            }
        }
    }
}
