//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class headerfooter_sr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal headerfooter_sr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("backend.Translations.headerfooter_sr", typeof(headerfooter_sr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string hul1 {
            get {
                return ResourceManager.GetString("hul1", resourceCulture);
            }
        }
        
        internal static string hul2 {
            get {
                return ResourceManager.GetString("hul2", resourceCulture);
            }
        }
        
        internal static string hul3 {
            get {
                return ResourceManager.GetString("hul3", resourceCulture);
            }
        }
        
        internal static string hul4 {
            get {
                return ResourceManager.GetString("hul4", resourceCulture);
            }
        }
        
        internal static string hul5 {
            get {
                return ResourceManager.GetString("hul5", resourceCulture);
            }
        }
        
        internal static string hul6 {
            get {
                return ResourceManager.GetString("hul6", resourceCulture);
            }
        }
        
        internal static string hul7 {
            get {
                return ResourceManager.GetString("hul7", resourceCulture);
            }
        }
        
        internal static string ful1p1 {
            get {
                return ResourceManager.GetString("ful1p1", resourceCulture);
            }
        }
        
        internal static string ful1p2 {
            get {
                return ResourceManager.GetString("ful1p2", resourceCulture);
            }
        }
        
        internal static string ful1p3 {
            get {
                return ResourceManager.GetString("ful1p3", resourceCulture);
            }
        }
        
        internal static string ful2p1 {
            get {
                return ResourceManager.GetString("ful2p1", resourceCulture);
            }
        }
        
        internal static string ful2p2 {
            get {
                return ResourceManager.GetString("ful2p2", resourceCulture);
            }
        }
        
        internal static string ful2p3 {
            get {
                return ResourceManager.GetString("ful2p3", resourceCulture);
            }
        }
        
        internal static string ful2p4 {
            get {
                return ResourceManager.GetString("ful2p4", resourceCulture);
            }
        }
        
        internal static string ful2p5 {
            get {
                return ResourceManager.GetString("ful2p5", resourceCulture);
            }
        }
        
        internal static string ful3p1 {
            get {
                return ResourceManager.GetString("ful3p1", resourceCulture);
            }
        }
        
        internal static string hul8 {
            get {
                return ResourceManager.GetString("hul8", resourceCulture);
            }
        }
        
        internal static string hul9 {
            get {
                return ResourceManager.GetString("hul9", resourceCulture);
            }
        }
    }
}
