//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("backend.Translations.index", typeof(index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string sec1h1reci {
            get {
                return ResourceManager.GetString("sec1h1reci", resourceCulture);
            }
        }
        
        internal static string sec1lblpostani {
            get {
                return ResourceManager.GetString("sec1lblpostani", resourceCulture);
            }
        }
        
        internal static string sec1btntext {
            get {
                return ResourceManager.GetString("sec1btntext", resourceCulture);
            }
        }
        
        internal static string sec1h1 {
            get {
                return ResourceManager.GetString("sec1h1", resourceCulture);
            }
        }
        
        internal static string sec1h2 {
            get {
                return ResourceManager.GetString("sec1h2", resourceCulture);
            }
        }
        
        internal static string sec1h3 {
            get {
                return ResourceManager.GetString("sec1h3", resourceCulture);
            }
        }
        
        internal static string sec1tb1 {
            get {
                return ResourceManager.GetString("sec1tb1", resourceCulture);
            }
        }
        
        internal static string sec1tb2 {
            get {
                return ResourceManager.GetString("sec1tb2", resourceCulture);
            }
        }
        
        internal static string sec1tb3 {
            get {
                return ResourceManager.GetString("sec1tb3", resourceCulture);
            }
        }
        
        internal static string sec2naslov {
            get {
                return ResourceManager.GetString("sec2naslov", resourceCulture);
            }
        }
        
        internal static string sec2text {
            get {
                return ResourceManager.GetString("sec2text", resourceCulture);
            }
        }
        
        internal static string sec3h1 {
            get {
                return ResourceManager.GetString("sec3h1", resourceCulture);
            }
        }
        
        internal static string sec3h2 {
            get {
                return ResourceManager.GetString("sec3h2", resourceCulture);
            }
        }
        
        internal static string sec3h3 {
            get {
                return ResourceManager.GetString("sec3h3", resourceCulture);
            }
        }
        
        internal static string sec3h4 {
            get {
                return ResourceManager.GetString("sec3h4", resourceCulture);
            }
        }
        
        internal static string sec3h5 {
            get {
                return ResourceManager.GetString("sec3h5", resourceCulture);
            }
        }
        
        internal static string sec3h6 {
            get {
                return ResourceManager.GetString("sec3h6", resourceCulture);
            }
        }
        
        internal static string sec3tb1 {
            get {
                return ResourceManager.GetString("sec3tb1", resourceCulture);
            }
        }
        
        internal static string sec3tb2 {
            get {
                return ResourceManager.GetString("sec3tb2", resourceCulture);
            }
        }
        
        internal static string sec3tb3 {
            get {
                return ResourceManager.GetString("sec3tb3", resourceCulture);
            }
        }
        
        internal static string sec3tb4 {
            get {
                return ResourceManager.GetString("sec3tb4", resourceCulture);
            }
        }
        
        internal static string sec3tb5 {
            get {
                return ResourceManager.GetString("sec3tb5", resourceCulture);
            }
        }
        
        internal static string sec3tb6 {
            get {
                return ResourceManager.GetString("sec3tb6", resourceCulture);
            }
        }
        
        internal static string sec4btntext {
            get {
                return ResourceManager.GetString("sec4btntext", resourceCulture);
            }
        }
        
        internal static string sec4tb1 {
            get {
                return ResourceManager.GetString("sec4tb1", resourceCulture);
            }
        }
        
        internal static string sec4tb2 {
            get {
                return ResourceManager.GetString("sec4tb2", resourceCulture);
            }
        }
        
        internal static string sec4h1 {
            get {
                return ResourceManager.GetString("sec4h1", resourceCulture);
            }
        }
        
        internal static string sec4h1i {
            get {
                return ResourceManager.GetString("sec4h1i", resourceCulture);
            }
        }
        
        internal static string sec4tb3 {
            get {
                return ResourceManager.GetString("sec4tb3", resourceCulture);
            }
        }
        
        internal static string sec1h1ne {
            get {
                return ResourceManager.GetString("sec1h1ne", resourceCulture);
            }
        }
        
        internal static string sec1h1izg {
            get {
                return ResourceManager.GetString("sec1h1izg", resourceCulture);
            }
        }
        
        internal static string postSomething {
            get {
                return ResourceManager.GetString("postSomething", resourceCulture);
            }
        }
        
        internal static string invalidPost {
            get {
                return ResourceManager.GetString("invalidPost", resourceCulture);
            }
        }
        
        internal static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        internal static string logintopost {
            get {
                return ResourceManager.GetString("logintopost", resourceCulture);
            }
        }
        
        internal static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        internal static string pers {
            get {
                return ResourceManager.GetString("pers", resourceCulture);
            }
        }
    }
}
