//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class kontakt {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal kontakt() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("backend.Translations.kontakt", typeof(kontakt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string h1naslov {
            get {
                return ResourceManager.GetString("h1naslov", resourceCulture);
            }
        }
        
        internal static string phIme {
            get {
                return ResourceManager.GetString("phIme", resourceCulture);
            }
        }
        
        internal static string phPrezime {
            get {
                return ResourceManager.GetString("phPrezime", resourceCulture);
            }
        }
        
        internal static string phEmail {
            get {
                return ResourceManager.GetString("phEmail", resourceCulture);
            }
        }
        
        internal static string phporuka {
            get {
                return ResourceManager.GetString("phporuka", resourceCulture);
            }
        }
        
        internal static string btnText {
            get {
                return ResourceManager.GetString("btnText", resourceCulture);
            }
        }
        
        internal static string val_required {
            get {
                return ResourceManager.GetString("val-required", resourceCulture);
            }
        }
        
        internal static string val_email {
            get {
                return ResourceManager.GetString("val-email", resourceCulture);
            }
        }
    }
}
