//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class korisnikpage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal korisnikpage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("backend.Translations.korisnikpage", typeof(korisnikpage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show personal trainers.
        /// </summary>
        public static string btnPrikaziPTrenere {
            get {
                return ResourceManager.GetString("btnPrikaziPTrenere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show trainers.
        /// </summary>
        public static string btnPrikaziTrenere {
            get {
                return ResourceManager.GetString("btnPrikaziTrenere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is already your trainer..
        /// </summary>
        public static string err4 {
            get {
                return ResourceManager.GetString("err4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no trainers available..
        /// </summary>
        public static string err5 {
            get {
                return ResourceManager.GetString("err5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User page:.
        /// </summary>
        public static string h1naslov {
            get {
                return ResourceManager.GetString("h1naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ime {
            get {
                return ResourceManager.GetString("ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na vašem profilu će se prikazati informacije o izabranim trenerima..
        /// </summary>
        public static string informacija {
            get {
                return ResourceManager.GetString("informacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string lblsort {
            get {
                return ResourceManager.GetString("lblsort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string op1 {
            get {
                return ResourceManager.GetString("op1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string op2 {
            get {
                return ResourceManager.GetString("op2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string pos {
            get {
                return ResourceManager.GetString("pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string prezime {
            get {
                return ResourceManager.GetString("prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose:.
        /// </summary>
        public static string primeni {
            get {
                return ResourceManager.GetString("primeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport:.
        /// </summary>
        public static string sport {
            get {
                return ResourceManager.GetString("sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve already sent a request to this trainer..
        /// </summary>
        public static string zahtev {
            get {
                return ResourceManager.GetString("zahtev", resourceCulture);
            }
        }
    }
}
