//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class korisnik {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal korisnik() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("backend.Translations.korisnik", typeof(korisnik).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration:.
        /// </summary>
        public static string aktivnePretplate {
            get {
                return ResourceManager.GetString("aktivnePretplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is already sent!.
        /// </summary>
        public static string alr {
            get {
                return ResourceManager.GetString("alr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string brojTelefona {
            get {
                return ResourceManager.GetString("brojTelefona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in date:.
        /// </summary>
        public static string datumRegistracije {
            get {
                return ResourceManager.GetString("datumRegistracije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth:.
        /// </summary>
        public static string datumRodjenja {
            get {
                return ResourceManager.GetString("datumRodjenja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head trainer.
        /// </summary>
        public static string glavniTrenerNaslov {
            get {
                return ResourceManager.GetString("glavniTrenerNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym:.
        /// </summary>
        public static string gym {
            get {
                return ResourceManager.GetString("gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gym.
        /// </summary>
        public static string gymNaslov {
            get {
                return ResourceManager.GetString("gymNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ime {
            get {
                return ResourceManager.GetString("ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change data.
        /// </summary>
        public static string izmeniPodatke {
            get {
                return ResourceManager.GetString("izmeniPodatke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data:.
        /// </summary>
        public static string licniPodaci {
            get {
                return ResourceManager.GetString("licniPodaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Trainer is not deleted. Try again later..
        /// </summary>
        public static string neuspesnoObrisan {
            get {
                return ResourceManager.GetString("neuspesnoObrisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete trainer.
        /// </summary>
        public static string obrisi {
            get {
                return ResourceManager.GetString("obrisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal trainer.
        /// </summary>
        public static string personalniTrenerNaslov {
            get {
                return ResourceManager.GetString("personalniTrenerNaslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diet plan:.
        /// </summary>
        public static string planIshrane {
            get {
                return ResourceManager.GetString("planIshrane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training plan:.
        /// </summary>
        public static string planTreninga {
            get {
                return ResourceManager.GetString("planTreninga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string prezime {
            get {
                return ResourceManager.GetString("prezime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training schedule:.
        /// </summary>
        public static string rasporedTreninga {
            get {
                return ResourceManager.GetString("rasporedTreninga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string sendRequest {
            get {
                return ResourceManager.GetString("sendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent!.
        /// </summary>
        public static string sent {
            get {
                return ResourceManager.GetString("sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer is successfully deleted..
        /// </summary>
        public static string uspesnoObrisan {
            get {
                return ResourceManager.GetString("uspesnoObrisan", resourceCulture);
            }
        }
    }
}
