//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class korpa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal korpa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("backend.Translations.korpa", typeof(korpa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string btnporuci {
            get {
                return ResourceManager.GetString("btnporuci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string btnText {
            get {
                return ResourceManager.GetString("btnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        internal static string h1naslov {
            get {
                return ResourceManager.GetString("h1naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment details.
        /// </summary>
        internal static string h2detalji {
            get {
                return ResourceManager.GetString("h2detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  indicates that the field is required.
        /// </summary>
        internal static string lbl_ {
            get {
                return ResourceManager.GetString("lbl*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string lblcena {
            get {
                return ResourceManager.GetString("lblcena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string lblkol {
            get {
                return ResourceManager.GetString("lblkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblnaziv {
            get {
                return ResourceManager.GetString("lblnaziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price:.
        /// </summary>
        internal static string lblukupnacena {
            get {
                return ResourceManager.GetString("lblukupnacena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string lblukupno {
            get {
                return ResourceManager.GetString("lblukupno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street and house number/apartment number*.
        /// </summary>
        internal static string phadresa {
            get {
                return ResourceManager.GetString("phadresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string phgrad {
            get {
                return ResourceManager.GetString("phgrad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string phnapomena {
            get {
                return ResourceManager.GetString("phnapomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        internal static string phpostbroj {
            get {
                return ResourceManager.GetString("phpostbroj", resourceCulture);
            }
        }
    }
}
