//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class korpa_sr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal korpa_sr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("backend.Translations.korpa_sr", typeof(korpa_sr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string h1naslov {
            get {
                return ResourceManager.GetString("h1naslov", resourceCulture);
            }
        }
        
        internal static string lblnaziv {
            get {
                return ResourceManager.GetString("lblnaziv", resourceCulture);
            }
        }
        
        internal static string lblcena {
            get {
                return ResourceManager.GetString("lblcena", resourceCulture);
            }
        }
        
        internal static string lblkol {
            get {
                return ResourceManager.GetString("lblkol", resourceCulture);
            }
        }
        
        internal static string lblukupno {
            get {
                return ResourceManager.GetString("lblukupno", resourceCulture);
            }
        }
        
        internal static string lblukupnacena {
            get {
                return ResourceManager.GetString("lblukupnacena", resourceCulture);
            }
        }
        
        internal static string btnText {
            get {
                return ResourceManager.GetString("btnText", resourceCulture);
            }
        }
        
        internal static string h2detalji {
            get {
                return ResourceManager.GetString("h2detalji", resourceCulture);
            }
        }
        
        internal static string btnporuci {
            get {
                return ResourceManager.GetString("btnporuci", resourceCulture);
            }
        }
        
        internal static string phgrad {
            get {
                return ResourceManager.GetString("phgrad", resourceCulture);
            }
        }
        
        internal static string phpostbroj {
            get {
                return ResourceManager.GetString("phpostbroj", resourceCulture);
            }
        }
        
        internal static string phadresa {
            get {
                return ResourceManager.GetString("phadresa", resourceCulture);
            }
        }
        
        internal static string phnapomena {
            get {
                return ResourceManager.GetString("phnapomena", resourceCulture);
            }
        }
        
        internal static string lbl_ {
            get {
                return ResourceManager.GetString("lbl*", resourceCulture);
            }
        }
    }
}
