//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class prodavnica_sr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal prodavnica_sr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("backend.Translations.prodavnica_sr", typeof(prodavnica_sr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string h1Odeca {
            get {
                return ResourceManager.GetString("h1Odeca", resourceCulture);
            }
        }
        
        public static string h1Obuca {
            get {
                return ResourceManager.GetString("h1Obuca", resourceCulture);
            }
        }
        
        public static string h1Operma {
            get {
                return ResourceManager.GetString("h1Operma", resourceCulture);
            }
        }
        
        public static string h1Suplementi {
            get {
                return ResourceManager.GetString("h1Suplementi", resourceCulture);
            }
        }
        
        public static string kat {
            get {
                return ResourceManager.GetString("kat", resourceCulture);
            }
        }
        
        public static string btnFilter {
            get {
                return ResourceManager.GetString("btnFilter", resourceCulture);
            }
        }
        
        public static string phod {
            get {
                return ResourceManager.GetString("phod", resourceCulture);
            }
        }
        
        public static string phdo {
            get {
                return ResourceManager.GetString("phdo", resourceCulture);
            }
        }
        
        public static string duks {
            get {
                return ResourceManager.GetString("duks", resourceCulture);
            }
        }
        
        public static string tren {
            get {
                return ResourceManager.GetString("tren", resourceCulture);
            }
        }
        
        public static string sorc {
            get {
                return ResourceManager.GetString("sorc", resourceCulture);
            }
        }
        
        public static string carape {
            get {
                return ResourceManager.GetString("carape", resourceCulture);
            }
        }
        
        public static string patike {
            get {
                return ResourceManager.GetString("patike", resourceCulture);
            }
        }
        
        public static string papuce {
            get {
                return ResourceManager.GetString("papuce", resourceCulture);
            }
        }
        
        public static string lblfiltirajpoceni {
            get {
                return ResourceManager.GetString("lblfiltirajpoceni", resourceCulture);
            }
        }
        
        public static string lblprikaz {
            get {
                return ResourceManager.GetString("lblprikaz", resourceCulture);
            }
        }
        
        public static string lblsort {
            get {
                return ResourceManager.GetString("lblsort", resourceCulture);
            }
        }
        
        public static string op1 {
            get {
                return ResourceManager.GetString("op1", resourceCulture);
            }
        }
        
        public static string op2 {
            get {
                return ResourceManager.GetString("op2", resourceCulture);
            }
        }
        
        public static string maijca {
            get {
                return ResourceManager.GetString("maijca", resourceCulture);
            }
        }
        
        public static string btnCena {
            get {
                return ResourceManager.GetString("btnCena", resourceCulture);
            }
        }
        
        public static string kategorija {
            get {
                return ResourceManager.GetString("kategorija", resourceCulture);
            }
        }
        
        public static string cena {
            get {
                return ResourceManager.GetString("cena", resourceCulture);
            }
        }
        
        public static string prikazivise {
            get {
                return ResourceManager.GetString("prikazivise", resourceCulture);
            }
        }
        
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
    }
}
