//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class registracija {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal registracija() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("backend.Translations.registracija", typeof(registracija).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string prekoGoogla {
            get {
                return ResourceManager.GetString("prekoGoogla", resourceCulture);
            }
        }
        
        internal static string lozinka {
            get {
                return ResourceManager.GetString("lozinka", resourceCulture);
            }
        }
        
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        internal static string ime {
            get {
                return ResourceManager.GetString("ime", resourceCulture);
            }
        }
        
        internal static string prezime {
            get {
                return ResourceManager.GetString("prezime", resourceCulture);
            }
        }
        
        internal static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        internal static string ilireg {
            get {
                return ResourceManager.GetString("ilireg", resourceCulture);
            }
        }
        
        internal static string datum {
            get {
                return ResourceManager.GetString("datum", resourceCulture);
            }
        }
        
        internal static string regkao {
            get {
                return ResourceManager.GetString("regkao", resourceCulture);
            }
        }
        
        internal static string btnReg {
            get {
                return ResourceManager.GetString("btnReg", resourceCulture);
            }
        }
        
        internal static string sel0 {
            get {
                return ResourceManager.GetString("sel0", resourceCulture);
            }
        }
        
        internal static string sel1 {
            get {
                return ResourceManager.GetString("sel1", resourceCulture);
            }
        }
        
        internal static string sel2 {
            get {
                return ResourceManager.GetString("sel2", resourceCulture);
            }
        }
        
        internal static string val_Email_length {
            get {
                return ResourceManager.GetString("val-Email-length", resourceCulture);
            }
        }
        
        internal static string val_required {
            get {
                return ResourceManager.GetString("val-required", resourceCulture);
            }
        }
        
        internal static string lblsport {
            get {
                return ResourceManager.GetString("lblsport", resourceCulture);
            }
        }
        
        internal static string val_password {
            get {
                return ResourceManager.GetString("val-password", resourceCulture);
            }
        }
        
        internal static string val_email {
            get {
                return ResourceManager.GetString("val-email", resourceCulture);
            }
        }
        
        internal static string val_EmailRegistered {
            get {
                return ResourceManager.GetString("val-EmailRegistered", resourceCulture);
            }
        }
        
        internal static string nalog {
            get {
                return ResourceManager.GetString("nalog", resourceCulture);
            }
        }
    }
}
