//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class trener_sr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal trener_sr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("backend.Translations.trener_sr", typeof(trener_sr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string h1naslov {
            get {
                return ResourceManager.GetString("h1naslov", resourceCulture);
            }
        }
        
        public static string lblsort {
            get {
                return ResourceManager.GetString("lblsort", resourceCulture);
            }
        }
        
        public static string op1 {
            get {
                return ResourceManager.GetString("op1", resourceCulture);
            }
        }
        
        public static string op2 {
            get {
                return ResourceManager.GetString("op2", resourceCulture);
            }
        }
        
        public static string btnPrikaziKlijente {
            get {
                return ResourceManager.GetString("btnPrikaziKlijente", resourceCulture);
            }
        }
        
        public static string btnPrikaziZahteve {
            get {
                return ResourceManager.GetString("btnPrikaziZahteve", resourceCulture);
            }
        }
        
        public static string primeni {
            get {
                return ResourceManager.GetString("primeni", resourceCulture);
            }
        }
    }
}
